# Generated by Django 3.2.15 on 2022-10-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='teaser',
            new_name='summary',
        ),
    ]
